Use symlinks to heroic to specify type of service.

diff --git a/src/deb/bin/heroic b/src/deb/bin/heroic
--- a/src/deb/bin/heroic
+++ b/src/deb/bin/heroic
@@ -1,10 +1,27 @@
 #!/bin/bash
 
 SHARE="/usr/share/heroic"
-JAR=$(echo $SHARE/heroic-*.jar)
-DEFAULT_JVMARGS="/etc/heroic/heroic.jvmargs"
-JVMARGS=${2-$DEFAULT_JVMARGS}
+CONFIG_DIR="/etc/heroic"
 
+base=$(basename $0)
+
+case $base in
+    heroic-*)
+        service_type=${base#*-}
+    ;;
+    "heroic")
+        service_type="api"
+        shift
+    ;;
+    *)
+        echo "Unknown invocation: $0"
+        exit 1
+    ;;
+esac
+
+JAR="$SHARE/heroic.jar"
+JVMARGS="${CONFIG_DIR}/heroic-${service_type}.jvmargs"
+CONFIG="${CONFIG_DIR}/heroic-${service_type}.yml"
 
 if [[ ! -f $JAR ]]; then
     echo "Missing heroic jar: $JAR"
@@ -16,6 +33,11 @@ if [[ ! -f $JVMARGS ]]; then
     exit 1
 fi
 
+if [[ ! -f $CONFIG ]]; then
+    echo "Missing config: $CONFIG"
+    exit 1
+fi
+
 JAVA_OPTS=$(grep -v '^\s*#' $JVMARGS)
 
-exec env CLASSPATH="$JAR" java $JAVA_OPTS com.spotify.heroic.Main "$@"
+exec env CLASSPATH="$JAR" java $JAVA_OPTS com.spotify.heroic.Main "$CONFIG"
